### ISSUE TITLE
 slim4-api-skeleton as docker container without mysql in container

### ISSUE THREAD

**Issue by StephanKrauss** [maurobonfietti/slim4-api-skeleton#27]
Hello,

i'm a beginner in docker.
This is my first test with slim4-api-skeleton.
I will use the slim4-api-skeleton in a container.
When i start docker-compose i see in the container is a maysql database.
Is there a way to use a external mysql database ?

Your sincerly

Stephan

**Comment by GoldraK** [comment]
Hi,
You only need change the config in .env file with your data.

```
DB_HOST='127.0.0.1'
DB_NAME='slim4_api_skeleton'
DB_USER='root'
DB_PASS=''
```

And delete this lines in docker-compose.yml

  ```
mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: slim4_api_skeleton
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    networks:
      - testingnetwork
    volumes:
      - my-data:/var/lib/mysql
```
