### ISSUE TITLE
About running the docker compose

### ISSUE THREAD

**Issue by mazecat** [maurobonfietti/slim4-api-skeleton#48]
I'm a beginner in docker beginner and try to using docker compose start up the project and check the db

but when I add a view for check db  in the docker-compose file, 

but it will display error message when I login

What problem in the docker compose  file? 

Ps. 
1. localhost:8080/
2. 127.0.0.1:8080/
1 and 2 not work go to page then login still show the error

Thanks.

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve
<img width="274" alt="2" src="https://user-images.githubusercontent.com/44782630/103454850-dc965a80-4d22-11eb-93b9-b53551dc2bb9.png">
<img width="326" alt="1" src="https://user-images.githubusercontent.com/44782630/103454851-dd2ef100-4d22-11eb-8a2f-14bf83115fe6.png">

<img width="746" alt="3" src="https://user-images.githubusercontent.com/44782630/103454849-da340080-4d22-11eb-9aec-b0da7d19d973.png">

**Comment by maurobonfietti** [comment]
Hi @mazecat !

In you adminer login, try to use the hostname "mysql" instead of "db".
Also, adminer need to use a mysql user password.

So, stop all your containers.
Edit your docker-compose.yaml and .env files.
Start docker containers with `composer up` or `docker-compose up -d --build`.

----

<img width="953" alt="Screen Shot 2021-01-02 at 14 05 39" src="https://user-images.githubusercontent.com/24535949/103462514-73075380-4d04-11eb-95e6-86edcbd6084c.png">

----

<img width="967" alt="Screen Shot 2021-01-02 at 14 05 53" src="https://user-images.githubusercontent.com/24535949/103462517-76024400-4d04-11eb-8121-bc60540224d8.png">

----

<img width="402" alt="Screen Shot 2021-01-02 at 14 06 04" src="https://user-images.githubusercontent.com/24535949/103462519-7995cb00-4d04-11eb-9c98-ce9600c265f2.png">

----

This is for example my docker-compose.yaml file:
```yaml
version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: slim4-api-skeleton-nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  php-fpm:
    build: ./docker/php7
    container_name: slim4-api-skeleton-php-container
    links:
      - mysql
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
    volumes:
     - ./:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: slim4_api_skeleton
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-data:
```

and this is my .env file:
```env
DB_HOST='mysql'
DB_NAME='slim4_api_skeleton'
DB_USER='root'
DB_PASS='example'
DB_PORT='3306'

DISPLAY_ERROR_DETAILS=true
SLIM_BASE_PATH=''
```

I hope it'll work for you.
GoodBye.-
